import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Ashutosh',
      email: 'apadhi6638@gmail.com',
      password: bcrypt.hashSync('#qwerty#'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 'Shreyam',
      email: 'shreyam@example.com',
      password: bcrypt.hashSync('23920'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'g92 ',
      slug: 'most used gaming keyboard',
      category: 'Gaming',
      image: '/image/keyboard1.jpg',
      price: 1,
      brand: ' Logitech',
      ratings: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'g68 gaming',
      slug: 'best review gaming keyboard',
      category: 'gaming',
      image: '/image/keyboard2.jpg',
      price: 1,
      brand: ' Logitech',
      ratings: 4,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'aora',
      slug: 'cheapest gaming keyboard',
      category: 'Gaming',
      image: '/image/keyboard7.jpg',
      price: 1,
      brand: ' Corsair',
      ratings: 4,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'blue switches',
      slug: 'most sound gaming switches',
      category: 'switch',
      image: '/image/keyboard4.jpg',
      price: 1,
      brand: ' Otamo',
      ratings: 4,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'red switches',
      slug: 'good quality gaming switches',
      category: 'switch',
      image: '/image/keyboard5.jpg',
      price: 1,
      brand: ' namo',
      ratings: 4,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'red switches',
      slug: 'cheapest sound gaming switches',
      category: 'switch',
      image: '/image/keyboard6.jpg',
      price: 1,
      brand: ' bamo',
      ratings: 4,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
};
export default data;
